version: '3.8'  
services:  
  postgres:
    container_name: postgres_db  
    image: postgres:15.6-alpine3.19
    restart: always  
    environment:  
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: library_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:  
      - "5433:5432"